### ISSUE TITLE
Main issue - moving cursors slows down my FPS to 10.

### ISSUE THREAD

**Issue by joff-dp** [coffincolors/winlator#88]
Hello,

I wrote another issue before but I would separate this one, which is actually the main problem.

Due to xinput setting, I got only one cursot ( the game one ). My games runs at 25/35 fps ( 15-25 in mobox )
But as soon as I mouve the mouse to orientate my character, it drops to 10 fps. As soon as I stop using mouse, I’m back to 25-35.

Any suggestion?
Thank you so much

Btw I’m using your first version, all the others are not working with my nvidia shield. Containers created but never opened..

**Comment by coffincolors** [comment]
For the container thing, I mentioned this in the other issue you made- but please try a Reinstall ImageFs on the latest build- it should fix that issue. I highly recommend moving away from v13 as well- it is much slower

**Comment by joff-dp** [comment]
Hello
Thank you so much for helping!
My android device : Nvidia Shield Pro 2019 , octa-core, 3 gb ram, GPU Tegra X1

First try : your first build, with wine 9.2 custom
All settings to performance

I tried different FPS:

With D3DWine :
- Battlefield 1942, two cursors , approx. 10 fps, drops to 4 if cursor moving 
- soldier of fortune 2, my android cursor is visible, not the ingame one. I can’t interact with the game. i tried alternative mouse : no success . Forcemouseoverride force : nope.
- Openmohaa ( medal of honor allied aussault ) - 30 fps, reduced to 7~10 when moving aim.

With CNCDdraw : 
battlefield 1942 : only ingame cursor ( good point! ) , still 10 fps, lowered to 4 when moving aim.

I tried MOHAA with older wine 8.0.2, FPS goes up to 42 ! But drops to 10 when moving mouse.

It seems that winlator has an excellent compatibility with openGL, much better than Mobox. 

Hypothesis : should I use one of the xinput fixes from the start menu?

**Comment by joff-dp** [comment]
I just re-tried version 7.1.3x Cmod Glibc v11R,
Reinstalled imageFS, but I still get a infinite loop on « starting up »
Is there another version I should try?
Thank you very much!

**Comment by nvidiadepop** [comment]
I just tried installing  Winlator-7.1.3b-Cmod-PROOT-v9fix1-release and i can open the container
so it seems there's a compatibility problem between the shield and your glibc releases.
inconsistenly, Mobox runs fine with wine 9.7 glibc , i can't understand
ps ; nvidiadepop is my desktop account

update; i tried to run "need for speed hot pursuit 2 demo". in fact, the FPS drops at any  time, whenever I move my mouse ( even during intro videos )

**Comment by Mart-01-oss** [comment]
Use Input bridge for now it works really well ,though it has alot of flags in /res /.dex

**Comment by nvidiadepop** [comment]
Can you provide some infomations about inputbridge ?
I always thought it was used for touchscreen controls.
Does it corrects mouse cursor ?
Thanks!

**Comment by Mart-01-oss** [comment]
> Can you provide some infomations about inputbridge ? I always thought it was used for touchscreen controls. Does it corrects mouse cursor ? Thanks!

 it using only Xinput  after you exec. ib.exe it will display the xinput controller after you run the app
you migh notice some input delay 
[VID_20250823_021059.zip](https://github.com/user-attachments/files/21944352/VID_20250823_021059.zip)

**Comment by nvidiadepop** [comment]
Thank you ! i guess i will require a little help .
i installed the APK, then installed and launched ib..exe , i clicked on the rotary icon on upper right screen
now, my mouse acts like a real mouse, but I don't have any cursor, except the blank one from Winlator ( which became useless )
there's a folder named profile, but I don't know how to use it.
thanks a lot !

Edit : okay, I just found out how to use a profile  . But still, my mouse cursor remains invisible
